name: energise_test_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.3.0
  easy_localization: ^3.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  google_maps_flutter: ^2.6.1
  hive: ^2.2.3
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
